INSERT IGNORE INTO USER (USERNAME, PASSWORD) VALUES ('admin', '$2y$12$ZvmO9dRutbvvCPeP40hk/uMp090uhBl91G18V1s1OfjWQjdj0soSi');
INSERT IGNORE INTO USER (USERNAME, PASSWORD) VALUES ('demo', '$2y$12$mvnI2sPrFNv8w1hQwzTN5ucneV2aqOQ6saSwGmCJ7A/ME2ugyJvbi');
INSERT IGNORE INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'USER');
INSERT IGNORE INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('admin', 'ADMIN');
INSERT IGNORE INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('demo', 'USER');